---

- name: "Create backend app directory"
  file:
    path: ~/backend-app
    state: directory

- name: "Copy artifact to backend server"
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/backend-app/artifact.tar.gz

- name: "Unarchive backend app files"
  unarchive:
    src: ~/backend-app/artifact.tar.gz
    dest: ~/backend-app
    remote_src: true

- name: "Install node dependencies"
  shell: |
    cd ~/backend-app
    npm i
    
- name: "Run node app with pm2"
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js